name: Deliver
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  projects:
    description: Projects to deliver (default is all)
    required: false
    default: '*'
  deliveryTarget:
    description: Delivery target (AppSource or Storage)
    required: true
  artifacts:
    description: The artifacts to deliver or a folder in which the artifacts have been downloaded
    required: true
  type:
    description: Type of delivery (CD or Release)
    required: false
    default: 'CD'
  atypes:
    description: Types of artifacts to deliver (Apps,Dependencies,TestApps)
    required: false
    default: 'Apps,Dependencies,TestApps'
  goLive:
    description: Promote AppSource App to Go Live?
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _actor: ${{ inputs.actor }}
        _token: ${{ inputs.token }}
        _projects: ${{ inputs.projects }}
        _deliveryTarget: ${{ inputs.deliveryTarget }}
        _artifacts: ${{ inputs.artifacts }}
        _type: ${{ inputs.type }}
        _atypes: ${{ inputs.atypes }}
        _goLive: ${{ inputs.goLive }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "Deliver" -Action {
          ${{ github.action_path }}/Deliver.ps1 -actor $ENV:_actor -token $ENV:_token -projects $ENV:_projects -deliveryTarget $ENV:_deliveryTarget -artifacts $ENV:_artifacts -type $ENV:_type -atypes $ENV:_atypes -goLive ($ENV:_goLive -eq 'true')
        }
branding:
  icon: terminal
  color: blue
