name: Pull Request Status Check
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "PullRequestStatusCheck" -Action {
          ${{ github.action_path }}/PullRequestStatusCheck.ps1
        }
branding:
  icon: terminal
  color: blue
