name: Read Settings
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  project:
    description: Project folder
    required: false
    default: '.'
  buildMode:
    description: Build mode
    required: false
    default: 'Default'
  workflowName:
    description: Workflow name for which the settings are to be read
    required: false
    default: ${{ github.workflow }}
  get:
    description: Specifies which properties to get from the settings file, default is all
    required: false
    default: ''
outputs:
  GitHubRunnerJson:
    description: GitHubRunner in compressed Json format
    value: ${{ steps.readsettings.outputs.GitHubRunnerJson }}
  GitHubRunnerShell:
    description: Shell for GitHubRunner jobs
    value: ${{ steps.readsettings.outputs.GitHubRunnerShell }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: readsettings
      env:
        _project: ${{ inputs.project }}
        _buildMode: ${{ inputs.buildMode }}
        _workflowName: ${{ inputs.workflowName }}
        _get: ${{ inputs.get }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "ReadSettings" -Action {
          ${{ github.action_path }}/ReadSettings.ps1 -project $ENV:_project -buildMode $ENV:_buildMode -workflowName $ENV:_workflowName -get $ENV:_get
        }
branding:
  icon: terminal
  color: blue
