name: Workflow Initialize
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actionsRepo:
    description: The repository of the action
    required: false
    default: ${{ github.action_repository }}
  actionsRef:
    description: The ref of the action
    required: false
    default: ${{ github.action_ref }}
outputs:
  telemetryScopeJson:
    description: A telemetryScope that covers the workflow
    value: ${{ steps.workflowinitialize.outputs.telemetryScopeJson }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: workflowinitialize
      env:
        _actionsRepo: ${{ inputs.actionsRepo }}
        _actionsRef: ${{ inputs.actionsRef }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "WorkflowInitialize" -Action {
          ${{ github.action_path }}/WorkflowInitialize.ps1 -actionsRepo $ENV:_actionsRepo -actionsRef $ENV:_actionsRef
        }
branding:
  icon: terminal
  color: blue
