name: Workflow Initialize
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  eventId:
    description: The event id of the initiating workflow
    required: true
outputs:
  correlationId:
    description: A correlation Id for the workflow
    value: ${{ steps.workflowinitialize.outputs.correlationId }}
  telemetryScopeJson:
    description: A telemetryScope that covers the workflow
    value: ${{ steps.workflowinitialize.outputs.telemetryScopeJson }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: workflowinitialize
      env:
        _eventId: ${{ inputs.eventId }}
      run: |
        $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
        try {
          ${{ github.action_path }}/WorkflowInitialize.ps1 -eventId $ENV:_eventId
        }
        catch {
          Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
          exit 1
        }
branding:
  icon: terminal
  color: blue
