name: Deploy
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  environmentName:
    description: Name of environment to deploy to
    required: true
  artifactsFolder:
    description: Path to the downloaded artifacts to deploy
    required: true
  type:
    description: Type of deployment (CD or Publish)
    required: false
    default: 'CD'
  deploymentEnvironmentsJson:
    description: The settings for all Deployment Environments
    required: true
outputs:
  environmentUrl:
    description: The URL of the deployed environment
    value: ${{ steps.Deploy.outputs.environmentUrl }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: Deploy
      env:
        _environmentName: ${{ inputs.environmentName }}
        _artifactsFolder: ${{ inputs.artifactsFolder }}
        _type: ${{ inputs.type }}
        _deploymentEnvironmentsJson: ${{ inputs.deploymentEnvironmentsJson }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "Deploy" -Action {
          ${{ github.action_path }}/Deploy.ps1 -environmentName $ENV:_environmentName -artifactsFolder $ENV:_artifactsFolder -type $ENV:_type -deploymentEnvironmentsJson $ENV:_deploymentEnvironmentsJson
        }
branding:
  icon: terminal
  color: blue
