name: Deploy
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  environmentName:
    description: Name of environment to deploy to
    required: true
  artifacts:
    description: The artifacts to deploy or a folder in which the artifacts have been downloaded
    required: true
  type:
    description: Type of deployment (CD or Publish)
    required: false
    default: 'CD'
  deploymentEnvironmentsJson:
    description: The settings for all Deployment Environments
    required: true
outputs:
  environmentUrl:
    description: The URL of the deployed environment
    value: ${{ steps.Deploy.outputs.environmentUrl }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: Deploy
      env:
        _token: ${{ inputs.token }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _environmentName: ${{ inputs.environmentName }}
        _artifacts: ${{ inputs.artifacts }}
        _type: ${{ inputs.type }}
        _deploymentEnvironmentsJson: ${{ inputs.deploymentEnvironmentsJson }}
      run: |
        $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
        try {
          ${{ github.action_path }}/Deploy.ps1 -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -environmentName $ENV:_environmentName -artifacts $ENV:_artifacts -type $ENV:_type -deploymentEnvironmentsJson $ENV:_deploymentEnvironmentsJson
        }
        catch {
          Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
          exit 1
        }
branding:
  icon: terminal
  color: blue
