name: Determine Projects to Build
author: Microsoft Corporation
description: Determines the projects to build based on the changes
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  maxBuildDepth:
    description: Specifies the maximum build depth suppored by the workflow running the action
    required: false
    default: '0'
outputs:
  ProjectsJson:
    description: An array of AL-Go projects in compressed JSON format
    value: ${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}
  SkippedProjectsJson:
    description: An array of Skipped AL-Go projects in compressed JSON format
    value: ${{ steps.determineProjectsToBuild.outputs.SkippedProjectsJson }}
  ProjectDependenciesJson:
    description: An object that holds the project dependencies in compressed JSON format
    value: ${{ steps.determineProjectsToBuild.outputs.ProjectDependenciesJson }}
  BuildOrderJson:
    description: An array of objects that determine that build order, including build dimensions
    value: ${{ steps.determineProjectsToBuild.outputs.BuildOrderJson }}
  BuildAllProjects:
    description: A flag that indicates whether to build all projects or only the modified ones
    value: ${{ steps.determineProjectsToBuild.outputs.BuildAllProjects }}
  BaselineWorkflowRunId:
    description: The ID of the workflow run containing last known good build, if we are doing incremental builds
    value: ${{ steps.determineProjectsToBuild.outputs.BaselineWorkflowRunId }}
  BaselineWorkflowSHA:
    description: The SHA of the last known good build, if we are doing incremental builds
    value: ${{ steps.determineProjectsToBuild.outputs.BaselineWorkflowSHA }}
runs:
  using: composite
  steps:
    - name: Determine Projects to Build
      shell: ${{ inputs.shell }}
      id: determineProjectsToBuild
      env:
        _maxBuildDepth: ${{ inputs.maxBuildDepth }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "DetermineProjectsToBuild" -Action {
          ${{ github.action_path }}/DetermineProjectsToBuild.Action.ps1 -baseFolder ${{ github.workspace }} -token ${{ github.token }} -maxBuildDepth $env:_maxBuildDepth
        }
branding:
  icon: terminal
  color: blue
