name: Verify PR Changes
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  token:
    description: The token to use for the GitHub API
    required: false
    default: ${{ github.token }}
  prBaseRepository:
    description: The name of the repository the PR is going to
    required: false
    default: ${{ github.event.pull_request.base.repo.full_name }}
  pullRequestId:
    description: The id of the pull request
    required: false
    default: ${{ github.event.pull_request.number }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _token: ${{ inputs.token }}
        _prBaseRepository: ${{ inputs.prBaseRepository }}
        _pullRequestId: ${{ inputs.pullRequestId }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "VerifyPRChanges" -Action {
          ${{ github.action_path }}/VerifyPRChanges.ps1 -token $ENV:_token -prBaseRepository $ENV:_prBaseRepository -pullRequestId $ENV:_pullRequestId
        }
branding:
  icon: terminal
  color: blue
