name: Read Secrets
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  gitHubSecrets:
    description: All GitHub Secrets in compressed JSON format
    required: true
  getSecrets:
    description: Comma-separated list of Secrets to get. Secrets preceded by an asterisk are returned encrypted
    required: true
  useGhTokenWorkflowForPush:
    description: Determines whether you want to use the GhTokenWorkflow secret for TokenForPush
    required: false
    default: 'false'
outputs:
  Secrets:
    description: All requested secrets in compressed JSON format
    value: ${{ steps.ReadSecrets.outputs.Secrets }}
  TokenForPush:
    description: The token to use when workflows are pushing changes (either directly, or via pull requests).
    value: ${{ steps.ReadSecrets.outputs.TokenForPush }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: ReadSecrets
      env:
        _getSecrets: ${{ inputs.getSecrets }}
        _useGhTokenWorkflowForPush: ${{ inputs.useGhTokenWorkflowForPush }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -ActionName "ReadSecrets" -Action {
          ${{ github.action_path }}/ReadSecrets.ps1 -gitHubSecrets '${{ inputs.gitHubSecrets }}' -getSecrets $ENV:_getSecrets -useGhTokenWorkflowForPush $ENV:_useGhTokenWorkflowForPush
        }
branding:
  icon: terminal
  color: blue
